/**
 * @file ASPID_FDCAN_NETWORK.h
 *
 * @brief This header file was generated by cantools version 42.0.3 Wed Jul 15 12:20:13 2026.
 *
 * @copyright Copyright (c) 2018-2019 Erik Moqvist
 *
 * @par License
 * The MIT License (MIT)
 *
 * Permission is hereby granted, free of charge, to any person
 * obtaining a copy of this software and associated documentation
 * files (the "Software"), to deal in the Software without
 * restriction, including without limitation the rights to use, copy,
 * modify, merge, publish, distribute, sublicense, and/or sell copies
 * of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be
 * included in all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
 * EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 * NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS
 * BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN
 * ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
 * CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

#ifndef ASPID_FDCAN_NETWORK_H
#define ASPID_FDCAN_NETWORK_H

#ifdef __cplusplus
extern "C" {
#endif

#include <stdint.h>
#include <stdbool.h>
#include <stddef.h>

#ifndef EINVAL
#    define EINVAL 22
#endif

/* Frame ids. */
#define ASPID_FDCAN_NETWORK_NAV_OUTPUT_FRAME_ID (0x01u)
#define ASPID_FDCAN_NETWORK_AIRBRAKE_OUTPUT_FRAME_ID (0x00u)

/* Frame lengths in bytes. */
#define ASPID_FDCAN_NETWORK_NAV_OUTPUT_LENGTH (0u)
#define ASPID_FDCAN_NETWORK_AIRBRAKE_OUTPUT_LENGTH (0u)

/* Extended or standard frame types. */
#define ASPID_FDCAN_NETWORK_NAV_OUTPUT_IS_EXTENDED (0)
#define ASPID_FDCAN_NETWORK_AIRBRAKE_OUTPUT_IS_EXTENDED (0)

/* Frame cycle times in milliseconds. */


/* Signal choices. */


/* Frame Names. */
#define ASPID_FDCAN_NETWORK_NAV_OUTPUT_NAME "Nav_output"
#define ASPID_FDCAN_NETWORK_AIRBRAKE_OUTPUT_NAME "Airbrake_output"

/* Signal Names. */


/**
 * Signals in message Nav_output.
 *
 * All signal values are as on the CAN bus.
 */
struct ASPID_FDCAN_NETWORK_nav_output_t {
    /**
     * Dummy signal in empty message.
     */
    uint8_t dummy;
};

/**
 * Signals in message Airbrake_output.
 *
 * All signal values are as on the CAN bus.
 */
struct ASPID_FDCAN_NETWORK_airbrake_output_t {
    /**
     * Dummy signal in empty message.
     */
    uint8_t dummy;
};

/**
 * Pack message Nav_output.
 *
 * @param[out] dst_p Buffer to pack the message into.
 * @param[in] src_p Data to pack.
 * @param[in] size Size of dst_p.
 *
 * @return Size of packed data, or negative error code.
 */
int ASPID_FDCAN_NETWORK_nav_output_pack(
    uint8_t *dst_p,
    const struct ASPID_FDCAN_NETWORK_nav_output_t *src_p,
    size_t size);

/**
 * Unpack message Nav_output.
 *
 * @param[out] dst_p Object to unpack the message into.
 * @param[in] src_p Message to unpack.
 * @param[in] size Size of src_p.
 *
 * @return zero(0) or negative error code.
 */
int ASPID_FDCAN_NETWORK_nav_output_unpack(
    struct ASPID_FDCAN_NETWORK_nav_output_t *dst_p,
    const uint8_t *src_p,
    size_t size);

/**
 * Init message fields to default values from Nav_output.
 *
 * @param[in] msg_p Message to init.
 *
 * @return zero(0) on success or (-1) in case of nullptr argument.
 */
int ASPID_FDCAN_NETWORK_nav_output_init(struct ASPID_FDCAN_NETWORK_nav_output_t *msg_p);

/**
 * Pack message Airbrake_output.
 *
 * @param[out] dst_p Buffer to pack the message into.
 * @param[in] src_p Data to pack.
 * @param[in] size Size of dst_p.
 *
 * @return Size of packed data, or negative error code.
 */
int ASPID_FDCAN_NETWORK_airbrake_output_pack(
    uint8_t *dst_p,
    const struct ASPID_FDCAN_NETWORK_airbrake_output_t *src_p,
    size_t size);

/**
 * Unpack message Airbrake_output.
 *
 * @param[out] dst_p Object to unpack the message into.
 * @param[in] src_p Message to unpack.
 * @param[in] size Size of src_p.
 *
 * @return zero(0) or negative error code.
 */
int ASPID_FDCAN_NETWORK_airbrake_output_unpack(
    struct ASPID_FDCAN_NETWORK_airbrake_output_t *dst_p,
    const uint8_t *src_p,
    size_t size);

/**
 * Init message fields to default values from Airbrake_output.
 *
 * @param[in] msg_p Message to init.
 *
 * @return zero(0) on success or (-1) in case of nullptr argument.
 */
int ASPID_FDCAN_NETWORK_airbrake_output_init(struct ASPID_FDCAN_NETWORK_airbrake_output_t *msg_p);


#ifdef __cplusplus
}
#endif

#endif
